//! [`EvmSubject`] — extends `nuke::Subject` with the EVM-specific
//! methods needed to open an `eth_subscribe("logs", ...)` and decode
//! the resulting notifications back into typed events.
//!
//! The framework's `nuke::Subject` is venue-agnostic. The EVM
//! adapter layers on the venue specifics here so adapter code can
//! bound on `EvmSubject` instead of hard-coding `nuke::Subject` +
//! ad-hoc helpers.

use alloy_primitives::Address;

use crate::DecodeError;
use crate::subscription::{RawLog, SubscriptionSpec};

/// EVM-specific extension of [`nuke::Subject`].
///
/// Implementations are usually generated by `#[derive(EvmSubject)]`,
/// which reads `#[nuke(event = ABI::Variant, address = "0x...")]`
/// and emits both the `nuke::Subject` impl and this trait's impl.
pub trait EvmSubject: nuke::Subject {
    /// On-chain address this subject listens to. Const-derived from
    /// the `#[nuke(address = "...")]` attribute.
    fn address() -> Address;

    /// Build the JSON-RPC subscription params (logs filter on the
    /// configured address + the event's `SIGNATURE_HASH`).
    fn subscription() -> SubscriptionSpec;

    /// Decode one wire log into a typed event. Defers to alloy's
    /// `SolEvent::decode_log_data`.
    ///
    /// # Errors
    ///
    /// Returns [`DecodeError`] when the log's topics or data don't
    /// match the expected ABI shape.
    fn decode(log: &RawLog) -> Result<Self::Event, DecodeError>;
}
