//! Type-level dependency lists, the computed event union, and the
//! generic walker that opens each dep against a transport.
//!
//! A reactor declares its [`Dependent::Deps`] as a chain of
//! [`Cons`]/[`Nil`] cells whose head is some [`Subject`]
//! (`Cons<A, Cons<B, Nil>>`). Naming mirrors event-sorcery's
//! `Dependent` / `EntityList` / `deps!` so the same idiom covers both
//! external streams and internal aggregates.
//!
//! # Computed event union
//!
//! For a chain `Cons<A, Cons<B, Nil>>`, [`DepList::Event`] is
//! `OneOf<(A::Id, A::Event), OneOf<(B::Id, B::Event), Never>>`. The
//! [`Never`] tail is what makes [`crate::OneOf`]'s `.exhaustive()`
//! chain a compile-time exhaustiveness check: forgetting an `.on(...)`
//! handler for any dep leaves the tail still containing one of its
//! variants, so `.exhaustive()` cannot type-check.
//!
//! # Injection
//!
//! [`HasDep<D>`] places a typed `(Id, Event)` into the right slot of
//! the union. The single-dep blanket impl on `Cons<D, Nil>` covers the
//! trivial case; multi-dep impls are generated by the
//! [`register_deps!`](crate::register_deps) helper that the
//! [`deps!`](crate::deps) macro invokes.
//!
//! # Walking
//!
//! [`Subscribe<L, T>`] is a generic walker over a [`DepList`]. Adopters
//! who add a new transport implement [`Transport`] once for the
//! transport type and [`Wire<D>`] for each dep family they support;
//! the recursion (blanket impls for [`Cons`] and [`Nil`]) lives here.
//!
//! See [`Subscribe`]'s docs for the type-level shape (why `Self` shrinks
//! during recursion while `L` stays fixed).

use std::future::Future;
use std::marker::PhantomData;
use std::pin::Pin;

use crate::one_of::OneOf;
use crate::subject::Subject;

// ---------------------------------------------------------------------
// Type-level list cells
// ---------------------------------------------------------------------

/// Type-level cons cell for building linked lists of deps.
pub struct Cons<Head, Tail>(PhantomData<(Head, Tail)>);

/// Terminal element for type-level dep lists.
pub struct Nil;

/// The "no value possible" tail of every fully-specified union.
///
/// `enum Never {}` - uninhabited, so a `match` on it compiles only when
/// every other arm is handled. This is what makes `.exhaustive()` a
/// compile-time check.
#[derive(Clone)]
pub enum Never {}

// ---------------------------------------------------------------------
// Reactor dep declaration
// ---------------------------------------------------------------------

/// Declares which deps a reactor reacts to.
///
/// Generated by the statement-position form of [`deps!`](crate::deps):
///
/// ```ignore
/// deps!(ArbBot, [UniV2WethUsdc, SushiV2WethUsdc]);
/// ```
pub trait Dependent: Send + Sync {
    /// Type-level list of deps this reactor handles.
    type Deps: DepList;
}

impl<R: Dependent> Dependent for std::sync::Arc<R> {
    type Deps = R::Deps;
}

// ---------------------------------------------------------------------
// Computed event union
// ---------------------------------------------------------------------

/// Trait on type-level dep lists that computes the discriminated
/// union event type.
///
/// `Cons<A, Cons<B, Nil>>` yields
/// `OneOf<(A::Id, A::Event), OneOf<(B::Id, B::Event), Never>>`.
pub trait DepList {
    type Event: Send;
}

impl DepList for Nil {
    type Event = Never;
}

impl<Head: Subject, Tail: DepList> DepList for Cons<Head, Tail> {
    type Event = OneOf<(Head::Id, Head::Event), Tail::Event>;
}

// ---------------------------------------------------------------------
// Injection: (Id, Event) -> union slot
// ---------------------------------------------------------------------

/// Inject a dep's `(Id, Event)` into the union computed for a
/// [`DepList`].
pub trait HasDep<D: Subject>: DepList {
    fn inject(id: D::Id, event: D::Event) -> Self::Event;
}

/// Blanket impl for single-element dep lists. Multi-element lists
/// get their impls from [`register_deps!`](crate::register_deps).
impl<D: Subject> HasDep<D> for Cons<D, Nil> {
    fn inject(id: D::Id, event: D::Event) -> Self::Event {
        OneOf::Here((id, event))
    }
}

// ---------------------------------------------------------------------
// Generic, transport-agnostic walker
// ---------------------------------------------------------------------

/// Boxed future returned by trait methods in this module. Kept as a
/// type alias to avoid `clippy::type_complexity` noise at every
/// signature - the boxing is unavoidable while [`Subscribe`] and
/// [`Wire`] are object-safe.
type BoxedFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// One transport against which a [`DepList`] can be opened.
///
/// A transport is a long-lived handle (a ws connection, an HTTP client,
/// an in-process bus, ...) that knows how to create per-dep wirings.
/// Implementors only need to declare the accumulator type via
/// [`Transport::Out`]; per-dep behavior lives in [`Wire<D>`] impls on
/// the same transport.
///
/// # The [`Transport::Out`] GAT
///
/// [`Transport::Out<L>`] is the value the walker hands back when it
/// finishes [`Subscribe::open_all`]. It is generic in the reactor's
/// target dep list `L` so per-list typing (e.g. decoders that emit
/// `<L as DepList>::Event`) survives end-to-end. The `L: 'static`
/// bound exists because accumulators routinely hold boxed closures
/// that close over `L`-typed values.
pub trait Transport: Send + Sync {
    /// Per-target-DepList accumulator the walker builds up.
    type Out<L: DepList + 'static>: Default + Send + 'static;
}

/// Per-dep wiring step on a [`Transport`].
///
/// One impl per (transport, dep family). The body of [`Wire::wire`]
/// is the only adapter-specific code in the open-all path: it reads
/// `D`'s associated types / consts (via [`Subject`] and any extension
/// trait the dep family agreed on) and mutates the transport's
/// accumulator with one entry for `D`.
///
/// Implementations are typically blanket over an adapter-side trait:
///
/// ```ignore
/// impl<H: MyAdapterDep> Wire<H> for MyTransport
/// where
///     /* whatever bounds H needs */
/// {
///     fn wire<'a, L>(&'a self, out: &'a mut Dispatcher<L>)
///         -> BoxedFuture<'a, nuke::Result<()>>
///     where L: DepList + HasDep<H> + 'static,
///     {
///         /* open one subscription, register one decoder */
///     }
/// }
/// ```
///
/// The `L: HasDep<D>` bound on [`Wire::wire`] is what lets the body
/// call `<L as HasDep<D>>::inject(id, event)` to place a decoded
/// payload into the reactor's typed event union.
pub trait Wire<D: Subject>: Transport {
    /// Open this dep against `self`, mutating the accumulator with one
    /// entry for `D`.
    fn wire<'a, L>(&'a self, out: &'a mut Self::Out<L>) -> BoxedFuture<'a, crate::Result<()>>
    where
        L: DepList + HasDep<D> + 'static;
}

/// Type-level walker. Implemented for every [`DepList`] via the
/// blanket impls below.
///
/// Callers parameterize this with `(L, T)` where `L` is the reactor's
/// full target dep list and `T` is the [`Transport`] to open against;
/// the implementing chain is [`Self`] (which equals `L` at the entry
/// call but shrinks during recursion). [`Subscribe::open_all`] returns
/// the transport's accumulator [`Transport::Out`].
///
/// # Type-level shape
///
/// [`Subscribe`] takes two list parameters because the *chain being
/// walked* shrinks at each recursion step while the *target list* the
/// accumulator is keyed by stays fixed:
///
/// - `Self` is the chain remaining to walk. `Cons<H, Tail>` recurses on
///   `Tail`, and `Nil` is the base case.
/// - `L` is the reactor's full original [`DepList`]. Every step's
///   [`Wire<H>::wire`] call uses `L` to invoke
///   `<L as HasDep<H>>::inject`, which places the decoded `(Id, Event)`
///   into the right slot of the reactor's typed event union. `L` does
///   not change during recursion.
pub trait Subscribe<L: DepList, T: Transport> {
    /// Walk this chain against `transport`, calling [`Wire<H>::wire`]
    /// once for each dep `H` and returning the accumulated
    /// [`Transport::Out`].
    fn open_all(transport: &T) -> BoxedFuture<'_, crate::Result<T::Out<L>>>;
}

/// Base case. Returns a fresh, empty [`Transport::Out`].
impl<L: DepList + 'static, T: Transport> Subscribe<L, T> for Nil {
    fn open_all(_transport: &T) -> BoxedFuture<'_, crate::Result<T::Out<L>>> {
        Box::pin(async { Ok(T::Out::<L>::default()) })
    }
}

/// Recursive step. Walks `Tail` first to build the accumulator, then
/// runs [`Wire<H>::wire`] to add the entry for `H`. The `L` parameter
/// is held fixed across the recursion so every step's `Wire` call can
/// inject into the same target union.
impl<H, Tail, L, T> Subscribe<L, T> for Cons<H, Tail>
where
    H: Subject,
    L: DepList + HasDep<H> + 'static,
    T: Transport + Wire<H>,
    Tail: Subscribe<L, T>,
{
    fn open_all(transport: &T) -> BoxedFuture<'_, crate::Result<T::Out<L>>> {
        Box::pin(async move {
            let mut out = Tail::open_all(transport).await?;
            <T as Wire<H>>::wire::<L>(transport, &mut out).await?;
            Ok(out)
        })
    }
}
