//! Inject a subject's `(Id, Event)` pair into a reactor's typed union.
//!
//! Mirrors event-sorcery's `HasEntity`. The blanket impl covers
//! single-element lists; multi-element lists get impls generated by the
//! `register_subjects!` arm of the [`subjects!`](crate::subjects) macro.

use crate::one_of::OneOf;
use crate::subject::Subject;
use crate::subscribed::{Cons, Nil, SubjectList};

/// Inject a subject's `(Id, Event)` into the union computed for a
/// [`SubjectList`].
pub trait HasSubject<S: Subject>: SubjectList {
    fn inject(id: S::Id, event: S::Event) -> Self::Event;
}

/// Blanket impl for single-element subject lists. Multi-element lists
/// get their impls from `register_subjects!`.
impl<S: Subject> HasSubject<S> for Cons<S, Nil> {
    fn inject(id: S::Id, event: S::Event) -> Self::Event {
        OneOf::Here((id, event))
    }
}
