//! Inject a dep's `(Id, Event)` pair into a reactor's typed union.
//!
//! The blanket impl covers single-element lists; multi-element lists
//! get impls generated by the `register_deps!` arm of the
//! [`deps!`](crate::deps) macro.

use crate::one_of::OneOf;
use crate::subject::Subject;
use crate::subscribed::{Cons, DepList, Nil};

/// Inject a dep's `(Id, Event)` into the union computed for a
/// [`DepList`].
pub trait HasDep<D: Subject>: DepList {
    fn inject(id: D::Id, event: D::Event) -> Self::Event;
}

/// Blanket impl for single-element dep lists. Multi-element lists
/// get their impls from `register_deps!`.
impl<D: Subject> HasDep<D> for Cons<D, Nil> {
    fn inject(id: D::Id, event: D::Event) -> Self::Event {
        OneOf::Here((id, event))
    }
}
