//! The [`Subject`] trait — something that emits typed on-chain events.
//!
//! Each pool / contract is its own *type*, with `address()` returning a
//! const-derived `alloy_primitives::Address`. The framework reads
//! `Subject` impls at compile time to know what to subscribe to and how
//! to decode notifications back into typed events.

use alloy_primitives::Address;
use std::fmt::{Debug, Display};

use crate::evm::{DecodeError, RawLog, SubscriptionSpec};

/// Something on a chain that emits typed events.
///
/// Usually derived via `#[derive(EvmSubject)]` rather than implemented
/// by hand. The derive reads `#[nuke(event = ABI::Variant, address =
/// "0x...")]` and fills everything in.
pub trait Subject: Send + Sync + 'static {
    /// Strongly-typed identifier. Prevents address mix-ups at compile
    /// time — for on-chain subjects this is usually a newtype around
    /// `Address`.
    type Id: Debug + Display + Clone + Send + Sync + 'static;

    /// Decoded event type. Usually generated by `alloy::sol!`.
    type Event: Debug + Send + Sync + 'static;

    /// Stable identifier for routing/telemetry; must not change after
    /// downstream consumers persist references to it.
    const NAME: &'static str;

    /// Bumped when the on-chain ABI / event schema this subject decodes
    /// from changes. Reserved for the schema reconciler that lands in a
    /// follow-up PR; the const is in v0 so the API is stable.
    const SCHEMA_VERSION: u64;

    /// On-chain address this subject listens to.
    fn address() -> Address;

    /// Build the JSON-RPC subscription params for this subject.
    fn subscription() -> SubscriptionSpec;

    /// Decode one wire log into a typed event.
    ///
    /// # Errors
    ///
    /// Returns [`DecodeError`] when the log's topics or data don't match
    /// the expected ABI shape.
    fn decode(log: &RawLog) -> Result<Self::Event, DecodeError>;
}
