//! Type-level dependency lists and the computed event union.
//!
//! A reactor declares its [`Dependent::Deps`] as a `Cons<A, Cons<B, Nil>>`
//! (usually via the [`deps!`](crate::deps) macro). The matching
//! [`DepList::Event`] is a discriminated union built from each dep's
//! `(Id, Event)`. Naming mirrors event-sorcery's `Dependent` /
//! `EntityList` / `deps!` so a reactor's deps list reads the same way
//! whether the dep is an external stream or an internal aggregate.

use std::marker::PhantomData;

use crate::one_of::OneOf;
use crate::subject::Subject;

/// Type-level cons cell for building linked lists of deps.
pub struct Cons<Head, Tail>(PhantomData<(Head, Tail)>);

/// Terminal element for type-level dep lists.
pub struct Nil;

/// The "no value possible" tail of every fully-specified union.
///
/// `enum Never {}` - uninhabited, so a `match` on it compiles only when
/// every other arm is handled. This is what makes `.exhaustive()` a
/// compile-time check.
#[derive(Clone)]
pub enum Never {}

/// Declares which deps a reactor reacts to.
///
/// Generated by the statement-position form of [`deps!`](crate::deps):
///
/// ```ignore
/// deps!(ArbBot, [UniV2WethUsdc, SushiV2WethUsdc]);
/// ```
pub trait Dependent: Send + Sync {
    /// Type-level list of deps this reactor handles.
    type Deps: DepList;
}

impl<R: Dependent> Dependent for std::sync::Arc<R> {
    type Deps = R::Deps;
}

/// Trait on type-level dep lists that computes the discriminated
/// union event type.
///
/// `Cons<A, Cons<B, Nil>>` yields
/// `OneOf<(A::Id, A::Event), OneOf<(B::Id, B::Event), Never>>`.
pub trait DepList {
    type Event: Send;
}

impl DepList for Nil {
    type Event = Never;
}

impl<Head: Subject, Tail: DepList> DepList for Cons<Head, Tail> {
    type Event = OneOf<(Head::Id, Head::Event), Tail::Event>;
}
