//! Type-level subject lists and the computed event union.
//!
//! A reactor declares its [`Subscribed::Subjects`] as a
//! `Cons<A, Cons<B, Nil>>` (usually via the [`subjects!`](crate::subjects)
//! macro). The matching [`SubjectList::Event`] is a discriminated union
//! built from each subject's `(Id, Event)`.

use std::marker::PhantomData;

use crate::one_of::OneOf;
use crate::subject::Subject;

/// Type-level cons cell for building linked lists of subjects.
pub struct Cons<Head, Tail>(PhantomData<(Head, Tail)>);

/// Terminal element for type-level subject lists.
pub struct Nil;

/// The "no value possible" tail of every fully-specified union.
///
/// `enum Never {}` — uninhabited, so a `match` on it compiles only when
/// every other arm is handled. This is what makes `.exhaustive()` a
/// compile-time check.
#[derive(Clone)]
pub enum Never {}

/// Declares which subjects a reactor handles.
///
/// Generated by the statement-position form of [`subjects!`](crate::subjects):
///
/// ```ignore
/// subjects!(ArbBot, [UniV2WethUsdc, SushiV2WethUsdc]);
/// ```
pub trait Subscribed: Send + Sync {
    /// Type-level list of subjects this reactor handles.
    type Subjects: SubjectList;
}

impl<R: Subscribed> Subscribed for std::sync::Arc<R> {
    type Subjects = R::Subjects;
}

/// Trait on type-level subject lists that computes the discriminated
/// union event type.
///
/// `Cons<A, Cons<B, Nil>>` yields
/// `OneOf<(A::Id, A::Event), OneOf<(B::Id, B::Event), Never>>`.
pub trait SubjectList {
    type Event: Send;
}

impl SubjectList for Nil {
    type Event = Never;
}

impl<Head: Subject, Tail: SubjectList> SubjectList for Cons<Head, Tail> {
    type Event = OneOf<(Head::Id, Head::Event), Tail::Event>;
}
