//! Type-level dependency lists, the computed event union, and the
//! exhaustive-match `.on(...).exhaustive()` chain.
//!
//! A "dep" is anything with a typed identifier and a typed event - an
//! [`EventSourced`](crate::EventSourced) entity, a `Subject` for an
//! external stream, an in-process channel, etc. Reactors declare which
//! deps they react to as a compile-time linked list of these
//! [`Dep`]-implementing types; the matching event-union type is
//! computed for them by [`DepList`], and the
//! [`OneOf`]`.on(...).exhaustive()` chain ensures the reactor handles
//! every dep at compile time.
//!
//! # Naming
//!
//! `Dependent` declares the list. `Deps` is the associated type. `DepList`
//! computes the event union. `HasDep<D>` injects a typed `(Id, Event)`
//! into the union slot for `D`. The [`deps!`](crate::deps) macro is the
//! sugar that generates both the `Dependent` impl and the per-dep
//! `HasDep` impls so the list is written once.
//!
//! # `Dep` vs framework-specific dep traits
//!
//! [`Dep`] is intentionally minimal - just `Id` and `Event` associated
//! types. Adopters typically define a richer trait per dep family
//! (e.g. `nuke::Subject` for external sources;
//! [`EventSourced`](crate::EventSourced) for cqrs/es entities) and
//! make it a refinement of [`Dep`] so dep-list machinery works
//! unchanged.

use std::future::Future;
use std::marker::PhantomData;
use std::pin::Pin;

// ---------------------------------------------------------------------
// The minimal Dep trait
// ---------------------------------------------------------------------

/// One dep in a [`Dependent::Deps`] list. Carries only the typed
/// identifier and event - the bare minimum the type-level list
/// machinery needs.
///
/// Adopter-defined dep traits (a `Subject` for external streams, an
/// [`EventSourced`] for internal aggregates) make [`Dep`] their
/// supertrait.
pub trait Dep: Send + Sync + 'static {
    /// Strongly-typed identifier for one occurrence of this dep.
    type Id: Send + Sync + 'static;
    /// Decoded event type this dep yields.
    type Event: Send + 'static;
}

// No blanket `impl<E: EventSourced> Dep for E`: that would conflict
// with the analogous blanket adopter crates need for their own dep
// families (e.g. `impl<S: nuke::Subject> Dep for S`). Adopters write
// one explicit `impl Dep for MyEventSourcedType` per dep type they
// want to expose, or the dep family's derive macro emits one as
// part of its expansion.

// ---------------------------------------------------------------------
// Type-level list cells + uninhabited tail
// ---------------------------------------------------------------------

/// Type-level cons cell for building linked lists of deps.
pub struct Cons<Head, Tail>(PhantomData<(Head, Tail)>);

/// Terminal element for type-level dep lists.
pub struct Nil;

/// The "no value possible" tail of every fully-specified union, and
/// also the canonical infallible-error type for entities whose
/// operations cannot fail.
///
/// `enum Never {}` - uninhabited, so a `match` on it compiles only when
/// every other arm is handled. This is what makes
/// [`Fold::exhaustive`] a compile-time check, and what lets it be
/// used as an `Error` for [`crate::EventSourced`] entities that don't
/// produce errors.
#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Never {}

impl std::fmt::Display for Never {
    fn fmt(&self, _: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match *self {}
    }
}

impl std::error::Error for Never {}

// ---------------------------------------------------------------------
// Reactor dep declaration
// ---------------------------------------------------------------------

/// Declares which deps a reactor reacts to.
///
/// Generated by the statement-position form of [`deps!`](crate::deps):
///
/// ```ignore
/// deps!(ArbBot, [UniV2WethUsdc, SushiV2WethUsdc]);
/// ```
pub trait Dependent: Send + Sync {
    /// Type-level list of deps this reactor handles.
    type Deps: DepList;
}

impl<R: Dependent> Dependent for std::sync::Arc<R> {
    type Deps = R::Deps;
}

// ---------------------------------------------------------------------
// Computed event union
// ---------------------------------------------------------------------

/// Trait on type-level dep lists that computes the discriminated
/// union event type.
///
/// `Cons<A, Cons<B, Nil>>` yields
/// `OneOf<(A::Id, A::Event), OneOf<(B::Id, B::Event), Never>>`.
pub trait DepList {
    type Event: Send;
}

impl DepList for Nil {
    type Event = Never;
}

impl<Head: Dep, Tail: DepList> DepList for Cons<Head, Tail> {
    type Event = OneOf<(Head::Id, Head::Event), Tail::Event>;
}

// ---------------------------------------------------------------------
// Injection: (Id, Event) -> union slot
// ---------------------------------------------------------------------

/// Inject a dep's `(Id, Event)` into the union computed for a
/// [`DepList`].
pub trait HasDep<D: Dep>: DepList {
    fn inject(id: D::Id, event: D::Event) -> Self::Event;
}

/// Blanket impl for single-element dep lists. Multi-element lists
/// get their impls from [`register_deps!`](crate::register_deps).
impl<D: Dep> HasDep<D> for Cons<D, Nil> {
    fn inject(id: D::Id, event: D::Event) -> Self::Event {
        OneOf::Here((id, event))
    }
}

// ---------------------------------------------------------------------
// OneOf + Fold (the .on(...).exhaustive() chain)
// ---------------------------------------------------------------------

/// Discriminated union of dep events, computed from a type-level dep
/// list. See [`DepList`].
#[derive(Clone)]
pub enum OneOf<Head, Tail> {
    Here(Head),
    There(Tail),
}

impl<Id, Event, Tail> OneOf<(Id, Event), Tail> {
    /// Handle the head dep in the union.
    ///
    /// Returns a [`Fold`] that you continue with `.on(...)` for each
    /// remaining dep; finish with `.exhaustive().await`.
    pub fn on<'a, T, F, Fut>(self, handler: F) -> Fold<BoxedFuture<'a, T>, Tail>
    where
        F: FnOnce(Id, Event) -> Fut,
        Fut: Future<Output = T> + Send + 'a,
    {
        match self {
            Self::Here((id, event)) => Fold::Done(Box::pin(handler(id, event))),
            Self::There(tail) => Fold::Remaining(tail),
        }
    }
}

impl<A> OneOf<A, Never> {
    /// Unwrap a single-dep union.
    ///
    /// Convenience for `Deps = deps![Single]` where the computed
    /// event is `OneOf<(Id, Event), Never>`.
    pub fn into_inner(self) -> A {
        match self {
            Self::Here(inner) => inner,
            Self::There(never) => match never {},
        }
    }
}

/// Intermediate result from folding handlers over a [`OneOf`] chain.
pub enum Fold<T, Remaining> {
    Done(T),
    Remaining(Remaining),
}

type BoxedFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

impl<'a, T, Id, Event, Tail> Fold<BoxedFuture<'a, T>, OneOf<(Id, Event), Tail>> {
    /// Handle the next dep in the union.
    pub fn on<F, Fut>(self, handler: F) -> Fold<BoxedFuture<'a, T>, Tail>
    where
        F: FnOnce(Id, Event) -> Fut,
        Fut: Future<Output = T> + Send + 'a,
    {
        match self {
            Fold::Done(fut) => Fold::Done(fut),
            Fold::Remaining(one_of) => match one_of {
                OneOf::Here((id, event)) => Fold::Done(Box::pin(handler(id, event))),
                OneOf::There(tail) => Fold::Remaining(tail),
            },
        }
    }
}

impl<T> Fold<T, Never> {
    /// Extract the result once every dep has been handled.
    ///
    /// Only available when the remaining tail is [`Never`] - i.e.,
    /// when every dep in the reactor's list has a corresponding
    /// `.on()` handler. Forgetting one is a compile error.
    pub fn exhaustive(self) -> T {
        match self {
            Self::Done(result) => result,
            Self::Remaining(never) => match never {},
        }
    }
}

// ---------------------------------------------------------------------
// Macros
// ---------------------------------------------------------------------

/// Build a type-level dep list from dep types.
///
/// Two forms, distinguished by syntax:
///
/// - **Type-position** `deps![A, B, C]` expands to a nested
///   `Cons<A, Cons<B, Cons<C, Nil>>>` type.
/// - **Statement-position** `deps!(Reactor, [A, B, C])` generates
///   `impl Dependent for Reactor` and [`HasDep<X>`] impls for each
///   dep - written once, no duplication.
#[macro_export]
macro_rules! deps {
    // Statement-position: generate Dependent + HasDep impls.
    ($reactor:ty, [$($dep:ty),+ $(,)?]) => {
        impl $crate::Dependent for $reactor {
            type Deps = $crate::deps![$($dep),+];
        }
        $crate::register_deps!($($dep),+);
    };

    // Type-position: expand to Cons chain.
    () => { $crate::Nil };
    ($head:ty $(, $tail:ty)* $(,)?) => {
        $crate::Cons<$head, $crate::deps![$($tail),*]>
    };
}

/// Generate [`HasDep`] impls for each dep in a list.
///
/// Low-level building block used by the statement-position form of
/// [`deps!`]. Prefer [`deps!`] directly.
#[macro_export]
macro_rules! register_deps {
    // Single dep: blanket `HasDep<D> for Cons<D, Nil>` covers it.
    ($single:ty) => {};

    // Multiple deps: walk the list and generate one impl per dep.
    ($($dep:ty),+ $(,)?) => {
        $crate::register_deps!(@impls [$($dep),+] [$($dep),+] []);
    };

    // All deps processed.
    (@impls [] [$($all:ty),+] [$($done:ty),*]) => {};

    // Generate HasDep for the current dep, then recurse.
    (@impls [$current:ty $(, $rest:ty)*] [$($all:ty),+] [$($done:ty),*]) => {
        impl $crate::HasDep<$current> for $crate::deps![$($all),+] {
            fn inject(
                id: <$current as $crate::Dep>::Id,
                event: <$current as $crate::Dep>::Event,
            ) -> <Self as $crate::DepList>::Event {
                $crate::register_deps!(@wrap [$($done),*] $crate::OneOf::Here((id, event)))
            }
        }
        $crate::register_deps!(@impls [$($rest),*] [$($all),+] [$($done,)* $current]);
    };

    // No wrapping needed (dep is at head).
    (@wrap [] $expr:expr) => { $expr };

    // Wrap in OneOf::There once per dep preceding `current`.
    (@wrap [$_head:ty $(, $rest:ty)*] $expr:expr) => {
        $crate::OneOf::There($crate::register_deps!(@wrap [$($rest),*] $expr))
    };
}
