//! Expansion for `#[derive(Domain)]`.
//!
//! Reads the struct's fields and emits two things:
//!
//! 1. A snake_case module beside the struct (e.g. `mod order`) with one
//!    pub fn per field. Each function returns a typed
//!    `nuke::policy::ast::Expr<TypeTag>` referencing the field -
//!    rule authors write `order::qty()` instead of stringly-typed
//!    `field::<QtyT>("order", "qty")`.
//! 2. An inherent `read_field(&self, name: &str) -> Option<SlotValue>`
//!    method on the struct so contexts can delegate to it instead of
//!    writing a giant `match` by hand.
//!
//! Field-type -> AST-type-tag mapping is hardcoded against the canonical
//! domain primitives (`Decimal`, `Px`, `Qty`, `Notional`, `Symbol`,
//! `Side`, `bool`).

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{Data, DeriveInput, Field, Fields, Ident, Type, TypePath, parse2};

pub(crate) fn expand(input: TokenStream) -> syn::Result<TokenStream> {
    let derive: DeriveInput = parse2(input)?;
    let struct_ident = derive.ident.clone();
    let struct_ident_str = struct_ident.to_string();
    let entity_name = to_snake_case(&struct_ident_str);
    let module_ident = format_ident!("{}", entity_name);

    let fields = struct_fields(&derive)?;
    let (accessors, read_arms): (Vec<TokenStream>, Vec<TokenStream>) = fields
        .into_iter()
        .map(|field| {
            let name_ident = field.ident.as_ref().ok_or_else(|| {
                syn::Error::new_spanned(field, "tuple structs are not supported")
            })?;
            let name_str = name_ident.to_string();
            let mapping = type_mapping(&field.ty)?;
            let tag = format_ident!("{}", mapping.tag);
            let slot = format_ident!("{}", mapping.slot_variant);
            let entity_lit = entity_name.clone();
            let name_lit = name_str.clone();

            let accessor = quote! {
                #[doc = concat!("Typed AST reference to `", #struct_ident_str, ".", #name_lit, "`.")]
                pub fn #name_ident()
                    -> ::nuke::policy::ast::Expr<::nuke::policy::ast::#tag>
                {
                    ::nuke::policy::ast::field::<::nuke::policy::ast::#tag>(#entity_lit, #name_lit)
                }
            };
            let read_arm = quote! {
                #name_lit => ::core::option::Option::Some(
                    ::nuke::policy::SlotValue::#slot(self.#name_ident.clone())
                ),
            };
            Ok::<_, syn::Error>((accessor, read_arm))
        })
        .collect::<syn::Result<Vec<_>>>()?
        .into_iter()
        .unzip();

    Ok(quote! {
        #[doc = concat!("Typed accessors for the `", #struct_ident_str, "` domain entity.")]
        pub mod #module_ident {
            use super::*;
            #(#accessors)*
        }

        impl #struct_ident {
            #[doc = concat!("Look up a field of `", #struct_ident_str, "` by name. Generated by `#[derive(Domain)]`.")]
            pub fn read_field(&self, name: &str) -> ::core::option::Option<::nuke::policy::SlotValue> {
                match name {
                    #(#read_arms)*
                    _ => ::core::option::Option::None,
                }
            }

            /// Stable entity name (snake_case of the struct name).
            pub const ENTITY_NAME: &'static str = #entity_name;
        }
    })
}

fn struct_fields(derive: &DeriveInput) -> syn::Result<Vec<&Field>> {
    let Data::Struct(data) = &derive.data else {
        return Err(syn::Error::new_spanned(
            &derive.ident,
            "#[derive(Domain)] only supports structs",
        ));
    };
    let Fields::Named(named) = &data.fields else {
        return Err(syn::Error::new_spanned(
            &derive.ident,
            "#[derive(Domain)] requires named fields",
        ));
    };
    Ok(named.named.iter().collect())
}

struct TypeMapping {
    tag: &'static str,
    slot_variant: &'static str,
}

fn type_mapping(ty: &Type) -> syn::Result<TypeMapping> {
    let last_segment = match ty {
        Type::Path(TypePath { path, .. }) => path
            .segments
            .last()
            .ok_or_else(|| syn::Error::new_spanned(ty, "expected a type with a path"))?,
        _ => {
            return Err(syn::Error::new_spanned(
                ty,
                "unsupported field type - must be one of: Decimal, Px, Qty, Notional, Symbol, Side, bool",
            ));
        }
    };
    let ident = &last_segment.ident;
    map_ident(ident)
        .ok_or_else(|| syn::Error::new_spanned(ty, format!("unsupported field type `{ident}`; expected one of: Decimal, Px, Qty, Notional, Symbol, Side, bool")))
}

fn map_ident(ident: &Ident) -> Option<TypeMapping> {
    match ident.to_string().as_str() {
        "Decimal" => Some(TypeMapping {
            tag: "DecT",
            slot_variant: "Decimal",
        }),
        "Px" => Some(TypeMapping {
            tag: "PxT",
            slot_variant: "Px",
        }),
        "Qty" => Some(TypeMapping {
            tag: "QtyT",
            slot_variant: "Qty",
        }),
        "Notional" => Some(TypeMapping {
            tag: "NotionalT",
            slot_variant: "Notional",
        }),
        "Symbol" => Some(TypeMapping {
            tag: "SymbolT",
            slot_variant: "Symbol",
        }),
        "Side" => Some(TypeMapping {
            tag: "SideT",
            slot_variant: "Side",
        }),
        "bool" => Some(TypeMapping {
            tag: "BoolT",
            slot_variant: "Bool",
        }),
        _ => None,
    }
}

fn to_snake_case(camel: &str) -> String {
    camel
        .chars()
        .enumerate()
        .flat_map(|(index, char)| {
            let lead = (index != 0 && char.is_uppercase()).then_some('_');
            let lowered: Box<dyn Iterator<Item = char>> = if char.is_uppercase() {
                Box::new(char.to_lowercase())
            } else {
                Box::new(std::iter::once(char))
            };
            lead.into_iter().chain(lowered)
        })
        .collect()
}
